fix vlfeat_slic_cli linking (pthread error)
Fixes the following error during compilation (linking):

/usr/bin/ld: ../../lib/libvlfeat.a(generic.c.o): undefined reference to symbol 'pthread_key_delete@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [../bin/vlfeat_slic_cli] Error 1
make[1]: *** [vlfeat_slic_cli/CMakeFiles/vlfeat_slic_cli.dir/all] Error 2
make: *** [all] Error 2

For more details, see:
http://stackoverflow.com/questions/25617839/undefined-reference-to-symbol-pthread-key-deleteglibc-2-2-5